#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CryptItMobile.Resource", IsApplication=true)]

namespace CryptItMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int backgroundMessage = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int endButton = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int head = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int listViewFriend = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int myMessage = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int silver = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int textButton = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int textFriend = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int textHint = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int textMessage = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int textMessageTime = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_disabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int loading = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int online = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int oval = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rectangle_rounded_all = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rectangle_rounded_bottom = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rectangle_rounded_top = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int dialogFriendImageView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dialogFriendTextView = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int dialogListView = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int enterButton = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int exitMainButton = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int friendImageView = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int friendMessageTextView = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int friendMessageTimeTextView = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int friendTextView = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int friendsListView = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int messageEditText = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int myMessageIsReadTextView = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int myMessageTextView = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int myMessageTimeTextView = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int newMessageTextView = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int onlineImageView = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int searchEditText = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int webView = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Friend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FriendMessage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int mainMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MyMessage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Start = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Exit = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Friends = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int InputMessage = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int InputName = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int NoPublicKey = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int Send = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
